"""empty message

Revision ID: 415e76170a82
Revises: 8aec6e473f69
Create Date: 2024-03-09 21:20:26.786628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "415e76170a82"
down_revision: Union[str, None] = "8aec6e473f69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("qr_code_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "qr_code_path")
    # ### end Alembic commands ###
